### ISSUE TITLE
comfyui打不开

### ISSUE THREAD

**Issue by shengshiai** [smthemex/ComfyUI_EchoMimic#19]
您好，请问一下comfyui打不开了
raise AssertionError（“Torch not compiled with CUDA enabled”）
AssertionError： Torch not compiled with CUDA enabled

**Comment by smthemex** [comment]
这样的情况多半是安装facenet_pytorch库时，因为pytorch版本不匹配，acenet_pytorch库关联卸载了又重新安装了pytorch。请按以下命令，打开CMD先卸载：pip uninstall torchaudio torchvision torch xformers
再重新安装
pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121
pip install xformers==0.0.24
pip install facenet_pytorch

**Comment by shengshiai** [comment]
实在太感谢了，已经解决了

**Comment by shengshiai** [comment]
> 这样的情况多半是安装facenet_pytorch库时，因为pytorch版本不匹配，acenet_pytorch库关联卸载了又重新安装了pytorch。请按以下命令，打开CMD先卸载：pip uninstall torchaudio torchvision torch xformers 再重新安装 pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121 pip install xformers==0.0.24 pip install facenet_pytorch

实在太感谢了，已经解决了
